"""
Functions to handle Excel file generated by BMKG website

Author: CHRN
Date: May 3, 2025
"""

import os
import xarray as xr
import numpy as np
import pandas as pd
from typing import List, Dict

# Set the option to opt-in to future behavior
# pd.set_option('future.no_silent_downcasting', True)

def list_excel_files_path (folder_dir: str) -> list[str]:
    '''Loop over each file in a folder directory, then store the paths if it is an Excel file'''

    # List all files in the directory
    files_dir = os.listdir(folder_dir)

    # Filter for Excel files based on their extension
    excel_files = [os.path.join(folder_dir, file) for file in files_dir if file.endswith('.xlsx') or file.endswith('.xls')]

    return excel_files

def read_excel_file_for_station_info (file_path: str) -> dict:
    '''Read an Excel file and returns station information as a dictionary'''

    # Read the Excel file
    df = pd.read_excel(file_path, nrows=7, header=None)

    # Obstain station info
    id_wmo  = df.iloc[0, 2][3:].strip()
    name    = df.iloc[1, 2][3:].strip()
    lat     = df.iloc[2, 2][3:].strip()
    lon     = df.iloc[3, 2][3:].strip()
    elev    = df.iloc[4, 2][3:].strip()

    # Construct station info dictionary
    station_info_dict = {'id_wmo'   : id_wmo,
                         'name'     : name,
                         'lat'      : lat,
                         'lon'      : lon,
                         'elev'     : elev}
    return station_info_dict

def read_excel_file_for_data (file_path: str) -> pd.DataFrame:
   '''Read a BMKG Excel file and keep all data as DataFrame'''

   # Read the Excel file
   df = pd.read_excel(file_path, skiprows=7)[:-16]

   return df

def check_data_completeness (df: pd.DataFrame, print_info: bool = False) -> None:
    '''Check data completeness: (1) availability of all ten variables and (2) length is more than 10 years'''
    
    # BMKG column names
    col_names = ['TANGGAL',	'TN', 'TX', 'TAVG', 'RH_AVG', 'RR', 'SS', 'FF_X', 'DDD_X', 'FF_AVG', 'DDD_CAR']


    # Check completeness of column in given data
    data_col_names = df.columns
    unavailable_col_names = []
    variables_are_complete = True

    for name in col_names:
        if name not in data_col_names:
            unavailable_col_names.append(name)
            variables_are_complete = False
    
    # Check data length (min. 10 years of observation)
    years = pd.DatetimeIndex(df['TANGGAL'], dayfirst=True).year
    yr_start, yr_end = years[0], years[-1]

    if (yr_end - yr_start) <= 10:
        is_more_than_10_years = False
    else:
        is_more_than_10_years = True

    # Print out info
    if print_info:
        if not variables_are_complete:
            print(f'Missing variables: {unavailable_col_names}')
        if not is_more_than_10_years:
            print('Data length is less than 10 years!')

    return variables_are_complete, unavailable_col_names, is_more_than_10_years

def wind_label_to_degree(label: str) -> float:
    """Convert wind direction label (e.g., 'N', 'NE', etc.) to meteorological degree."""

    # Strip label
    label = str(label).strip()

    # Define direction dictionary/map
    direction_map = {
        'C': -999,  # Calm
        'N': 0,
        'NE': 45,
        'E': 90,
        'SE': 135,
        'S': 180,
        'SW': 225,
        'W': 270,
        'NW': 315
    }
    return direction_map.get(label.upper(), np.nan)  # return np.nan if unknown label

def clean_data (df: pd.DataFrame) -> pd.DataFrame:
    '''Clean data by (1) removing missing values to nan, (2) dropping duplicates, (3) complete missing dates'''

    # BMKG variable column names
    var_col_names = ['TN', 'TX', 'TAVG', 'RH_AVG', 'RR', 'SS', 'FF_X', 'DDD_X', 'FF_AVG', 'DDD_CAR']

    # Reformat date
    df['TANGGAL'] = pd.to_datetime(df['TANGGAL'], dayfirst=True)
    
    # Filter missing values on each column
    for col in var_col_names:
        if col == 'DDD_CAR':
            df[col] = df[col].apply(wind_label_to_degree)
        else:
            df[col] = pd.to_numeric(df[col].astype(str).replace(['8888', '9999', '-'], np.nan), errors='coerce')

    # Drop duplicates
    df = df.drop_duplicates(subset='TANGGAL', keep='first')
    
    # Complete missing dates in time column
    df = df.set_index('TANGGAL').asfreq('D')

    # Force as numeric
    df = df.apply(pd.to_numeric, errors='coerce')

    return df

def create_netcdf(station_info_list: List[Dict[str, str]], data_list: List[pd.DataFrame], output_file: str):
    # Determine the common time range
    start_date = min(df.index.min() for df in data_list)
    end_date = max(df.index.max() for df in data_list)
    common_time_index = pd.date_range(start=start_date, end=end_date, freq='D')
    
    # Define the data structure
    station_ids = [info['id_wmo'] for info in station_info_list]
    station_names = [info['name'] for info in station_info_list]
    latitudes = np.array([float(info['lat']) for info in station_info_list])
    longitudes = np.array([float(info['lon']) for info in station_info_list])
    elevations = np.array([float(info['elev'].split()[0]) for info in station_info_list])

    # Define the variable names and their long names
    variable_names = [
        'RH_AVG', 'TAVG', 'FF_AVG', 'TX', 'FF_X', 'TN', 'RR', 'SS', 'DDD_X', 'DDD_CAR'
    ]
    long_names = [
        'Average Relative Humidity', 'Average Temperature', 'Average Wind Speed', 'Maximum Temperature',
        'Maximum Wind Speed', 'Minimum Temperature', 'Rainfall', 'Duration of Solar Radiation',
        'Wind Direction at Maximum Speed', 'Wind Direction Most Frequent'
    ]

    # Create the dataset
    ds = xr.Dataset(
        {
            var_name: (('station', 'time'), [df.reindex(common_time_index)[var_name].astype(float).values for df in data_list])
            for var_name in variable_names
        },
        coords={
            'station': station_ids,
            'station_name': ('station', station_names),
            'latitude': ('station', latitudes, {'units': 'degrees_north'}),
            'longitude': ('station', longitudes, {'units': 'degrees_east'}),
            'elevation': ('station', elevations, {'units': 'meters'}),
            'time': common_time_index
        },
        attrs={
            'title': 'Meteorological Data Around Indonesia',
            'source': 'BMKG Website',
            'description': '''
            Meteorological data collected from BMKG website in April 2025. BMKG website can be accessed through
            https://dataonline.bmkg.go.id/data-harian. Data collection by WADC, BATS, CHRN, and ABDM3. Data storing by CHRN.
            '''
        }
    )

    # for var_name in variable_names:
    #     for df in data_list:
    #         print(df.reindex(common_time_index)[var_name].astype(float).values)

    # Assign long names and units to each variable
    units = ['%', '°C', 'm/s', '°C', 'm/s', '°C', 'mm', 'hours', '°', '°']
    for var_name, long_name, unit in zip(variable_names, long_names, units):
        ds[var_name].attrs['long_name'] = long_name
        ds[var_name].attrs['units'] = unit

    # Add description to DDD_CAR for calm direction
    ds['DDD_CAR'].attrs['description'] = 'A value of -999 indicates calm direction.'

    # Save to NetCDF
    ds.to_netcdf(output_file)
    print(f'NetCDF file created: {output_file}')
    return ds